AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - '_scratchpad.rb'
    - 'lib/draftking/future_queue_methods.rb'
    - 'readme/generate_readme.rb'
    - 'tumblr_draftking.gemspec'

Style/GlobalVars:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'codeclimate.rb'
    - 'lib/draftking/cli_options.rb'
    - 'test/*.rb'
