
# Offense count: 12
Metrics/AbcSize:
  Max: 41

# Offense count: 1
Metrics/BlockNesting:
  Max: 4

# Offense count: 1
Metrics/CyclomaticComplexity:
  Max: 12

# Offense count: 32
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 167

# Offense count: 11
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 41

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 110


# Offense count: 5
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

# Offense count: 1
Style/MultilineTernaryOperator:
  Exclude:
    - 'bin/dk'
